name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake.svg with months visible
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg?palette=github-dark&color_snake=#00FF00&color_dots=#ebedf0,#9be9a8,#40c463,#30a14e,#216e39&grid_size=20&speed=0.6&animate=true&fill=true&loop=true&show_months=true&show_days=true&show_month_labels=true
